// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.8
// source: pb/scanner_simple.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 健康检查
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pb_scanner_simple_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scanner_simple_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pb_scanner_simple_proto_rawDescGZIP(), []int{0}
}

func (x *HealthRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pb_scanner_simple_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scanner_simple_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pb_scanner_simple_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 扫描请求 - 使用JSON字符串简化复杂配置
type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // 配置以JSON格式传递
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_pb_scanner_simple_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scanner_simple_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_pb_scanner_simple_proto_rawDescGZIP(), []int{2}
}

func (x *ScanRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ScanRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ScanRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_pb_scanner_simple_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scanner_simple_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_pb_scanner_simple_proto_rawDescGZIP(), []int{3}
}

func (x *ScanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScanResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 状态查询
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pb_scanner_simple_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scanner_simple_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_pb_scanner_simple_proto_rawDescGZIP(), []int{4}
}

func (x *StatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pb_scanner_simple_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scanner_simple_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pb_scanner_simple_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 结果查询
type ResultRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// 增量获取参数
	Offset        int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`           // 从第几个结果开始获取（0表示从头开始）
	Limit         int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`             // 最多获取多少个结果（0表示获取所有）
	Incremental   bool  `protobuf:"varint,4,opt,name=incremental,proto3" json:"incremental,omitempty"` // 是否只获取新增的结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_pb_scanner_simple_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scanner_simple_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_pb_scanner_simple_proto_rawDescGZIP(), []int{6}
}

func (x *ResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ResultRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ResultRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ResultRequest) GetIncremental() bool {
	if x != nil {
		return x.Incremental
	}
	return false
}

// 检测结果结构
type DetectionResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Url                string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Parameter          string                 `protobuf:"bytes,2,opt,name=parameter,proto3" json:"parameter,omitempty"`
	Payload            string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadSuccessFlag string                 `protobuf:"bytes,4,opt,name=payload_success_flag,json=payloadSuccessFlag,proto3" json:"payload_success_flag,omitempty"`
	Details            string                 `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	ScriptName         string                 `protobuf:"bytes,6,opt,name=script_name,json=scriptName,proto3" json:"script_name,omitempty"`
	RequestRaw         []byte                 `protobuf:"bytes,7,opt,name=request_raw,json=requestRaw,proto3" json:"request_raw,omitempty"`
	ResponseRaw        []byte                 `protobuf:"bytes,8,opt,name=response_raw,json=responseRaw,proto3" json:"response_raw,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DetectionResult) Reset() {
	*x = DetectionResult{}
	mi := &file_pb_scanner_simple_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionResult) ProtoMessage() {}

func (x *DetectionResult) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scanner_simple_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionResult.ProtoReflect.Descriptor instead.
func (*DetectionResult) Descriptor() ([]byte, []int) {
	return file_pb_scanner_simple_proto_rawDescGZIP(), []int{7}
}

func (x *DetectionResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DetectionResult) GetParameter() string {
	if x != nil {
		return x.Parameter
	}
	return ""
}

func (x *DetectionResult) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *DetectionResult) GetPayloadSuccessFlag() string {
	if x != nil {
		return x.PayloadSuccessFlag
	}
	return ""
}

func (x *DetectionResult) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *DetectionResult) GetScriptName() string {
	if x != nil {
		return x.ScriptName
	}
	return ""
}

func (x *DetectionResult) GetRequestRaw() []byte {
	if x != nil {
		return x.RequestRaw
	}
	return nil
}

func (x *DetectionResult) GetResponseRaw() []byte {
	if x != nil {
		return x.ResponseRaw
	}
	return nil
}

// 扫描任务信息
type ScanTaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Progress      int32                  `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	StartTime     string                 `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	WebhookUrl    string                 `protobuf:"bytes,8,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanTaskInfo) Reset() {
	*x = ScanTaskInfo{}
	mi := &file_pb_scanner_simple_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanTaskInfo) ProtoMessage() {}

func (x *ScanTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scanner_simple_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanTaskInfo.ProtoReflect.Descriptor instead.
func (*ScanTaskInfo) Descriptor() ([]byte, []int) {
	return file_pb_scanner_simple_proto_rawDescGZIP(), []int{8}
}

func (x *ScanTaskInfo) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ScanTaskInfo) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ScanTaskInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScanTaskInfo) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ScanTaskInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScanTaskInfo) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ScanTaskInfo) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ScanTaskInfo) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

type ResultResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TaskId      string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ResultsJson string                 `protobuf:"bytes,2,opt,name=results_json,json=resultsJson,proto3" json:"results_json,omitempty"` // 结果以JSON格式返回
	TotalCount  int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// 新增结构化字段
	TaskInfo         *ScanTaskInfo      `protobuf:"bytes,4,opt,name=task_info,json=taskInfo,proto3" json:"task_info,omitempty"`
	DetectionResults []*DetectionResult `protobuf:"bytes,5,rep,name=detection_results,json=detectionResults,proto3" json:"detection_results,omitempty"`
	Logs             []string           `protobuf:"bytes,6,rep,name=logs,proto3" json:"logs,omitempty"`
	// 增量获取相关字段
	CurrentOffset int32 `protobuf:"varint,7,opt,name=current_offset,json=currentOffset,proto3" json:"current_offset,omitempty"` // 当前返回结果的起始偏移量
	ReturnedCount int32 `protobuf:"varint,8,opt,name=returned_count,json=returnedCount,proto3" json:"returned_count,omitempty"` // 本次返回的结果数量
	HasMore       bool  `protobuf:"varint,9,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                   // 是否还有更多结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	mi := &file_pb_scanner_simple_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scanner_simple_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_pb_scanner_simple_proto_rawDescGZIP(), []int{9}
}

func (x *ResultResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ResultResponse) GetResultsJson() string {
	if x != nil {
		return x.ResultsJson
	}
	return ""
}

func (x *ResultResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ResultResponse) GetTaskInfo() *ScanTaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

func (x *ResultResponse) GetDetectionResults() []*DetectionResult {
	if x != nil {
		return x.DetectionResults
	}
	return nil
}

func (x *ResultResponse) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ResultResponse) GetCurrentOffset() int32 {
	if x != nil {
		return x.CurrentOffset
	}
	return 0
}

func (x *ResultResponse) GetReturnedCount() int32 {
	if x != nil {
		return x.ReturnedCount
	}
	return 0
}

func (x *ResultResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_pb_scanner_simple_proto protoreflect.FileDescriptor

const file_pb_scanner_simple_proto_rawDesc = "" +
	"\n" +
	"\x17pb/scanner_simple.proto\x12\ascanner\"(\n" +
	"\rHealthRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"X\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"_\n" +
	"\vScanRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\tR\n" +
	"configJson\"[\n" +
	"\fScanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\"(\n" +
	"\rStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"w\n" +
	"\x0eStatusResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"x\n" +
	"\rResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12 \n" +
	"\vincremental\x18\x04 \x01(\bR\vincremental\"\x8c\x02\n" +
	"\x0fDetectionResult\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1c\n" +
	"\tparameter\x18\x02 \x01(\tR\tparameter\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x120\n" +
	"\x14payload_success_flag\x18\x04 \x01(\tR\x12payloadSuccessFlag\x12\x18\n" +
	"\adetails\x18\x05 \x01(\tR\adetails\x12\x1f\n" +
	"\vscript_name\x18\x06 \x01(\tR\n" +
	"scriptName\x12\x1f\n" +
	"\vrequest_raw\x18\a \x01(\fR\n" +
	"requestRaw\x12!\n" +
	"\fresponse_raw\x18\b \x01(\fR\vresponseRaw\"\xe8\x01\n" +
	"\fScanTaskInfo\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x05R\bprogress\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\tR\aendTime\x12\x1f\n" +
	"\vwebhook_url\x18\b \x01(\tR\n" +
	"webhookUrl\"\xe5\x02\n" +
	"\x0eResultResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12!\n" +
	"\fresults_json\x18\x02 \x01(\tR\vresultsJson\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x122\n" +
	"\ttask_info\x18\x04 \x01(\v2\x15.scanner.ScanTaskInfoR\btaskInfo\x12E\n" +
	"\x11detection_results\x18\x05 \x03(\v2\x18.scanner.DetectionResultR\x10detectionResults\x12\x12\n" +
	"\x04logs\x18\x06 \x03(\tR\x04logs\x12%\n" +
	"\x0ecurrent_offset\x18\a \x01(\x05R\rcurrentOffset\x12%\n" +
	"\x0ereturned_count\x18\b \x01(\x05R\rreturnedCount\x12\x19\n" +
	"\bhas_more\x18\t \x01(\bR\ahasMore2\x91\x02\n" +
	"\x0eScannerService\x12>\n" +
	"\vHealthCheck\x12\x16.scanner.HealthRequest\x1a\x17.scanner.HealthResponse\x12:\n" +
	"\vExecuteScan\x12\x14.scanner.ScanRequest\x1a\x15.scanner.ScanResponse\x12@\n" +
	"\rGetScanStatus\x12\x16.scanner.StatusRequest\x1a\x17.scanner.StatusResponse\x12A\n" +
	"\x0eGetScanResults\x12\x16.scanner.ResultRequest\x1a\x17.scanner.ResultResponseB!Z\x1fwebScanner/common/grpcserver/pbb\x06proto3"

var (
	file_pb_scanner_simple_proto_rawDescOnce sync.Once
	file_pb_scanner_simple_proto_rawDescData []byte
)

func file_pb_scanner_simple_proto_rawDescGZIP() []byte {
	file_pb_scanner_simple_proto_rawDescOnce.Do(func() {
		file_pb_scanner_simple_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_scanner_simple_proto_rawDesc), len(file_pb_scanner_simple_proto_rawDesc)))
	})
	return file_pb_scanner_simple_proto_rawDescData
}

var file_pb_scanner_simple_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pb_scanner_simple_proto_goTypes = []any{
	(*HealthRequest)(nil),   // 0: scanner.HealthRequest
	(*HealthResponse)(nil),  // 1: scanner.HealthResponse
	(*ScanRequest)(nil),     // 2: scanner.ScanRequest
	(*ScanResponse)(nil),    // 3: scanner.ScanResponse
	(*StatusRequest)(nil),   // 4: scanner.StatusRequest
	(*StatusResponse)(nil),  // 5: scanner.StatusResponse
	(*ResultRequest)(nil),   // 6: scanner.ResultRequest
	(*DetectionResult)(nil), // 7: scanner.DetectionResult
	(*ScanTaskInfo)(nil),    // 8: scanner.ScanTaskInfo
	(*ResultResponse)(nil),  // 9: scanner.ResultResponse
}
var file_pb_scanner_simple_proto_depIdxs = []int32{
	8, // 0: scanner.ResultResponse.task_info:type_name -> scanner.ScanTaskInfo
	7, // 1: scanner.ResultResponse.detection_results:type_name -> scanner.DetectionResult
	0, // 2: scanner.ScannerService.HealthCheck:input_type -> scanner.HealthRequest
	2, // 3: scanner.ScannerService.ExecuteScan:input_type -> scanner.ScanRequest
	4, // 4: scanner.ScannerService.GetScanStatus:input_type -> scanner.StatusRequest
	6, // 5: scanner.ScannerService.GetScanResults:input_type -> scanner.ResultRequest
	1, // 6: scanner.ScannerService.HealthCheck:output_type -> scanner.HealthResponse
	3, // 7: scanner.ScannerService.ExecuteScan:output_type -> scanner.ScanResponse
	5, // 8: scanner.ScannerService.GetScanStatus:output_type -> scanner.StatusResponse
	9, // 9: scanner.ScannerService.GetScanResults:output_type -> scanner.ResultResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_scanner_simple_proto_init() }
func file_pb_scanner_simple_proto_init() {
	if File_pb_scanner_simple_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_scanner_simple_proto_rawDesc), len(file_pb_scanner_simple_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_scanner_simple_proto_goTypes,
		DependencyIndexes: file_pb_scanner_simple_proto_depIdxs,
		MessageInfos:      file_pb_scanner_simple_proto_msgTypes,
	}.Build()
	File_pb_scanner_simple_proto = out.File
	file_pb_scanner_simple_proto_goTypes = nil
	file_pb_scanner_simple_proto_depIdxs = nil
}
