package utils

var RequestCn requestCn

type requestCn struct {
}

func (r requestCn) AllCnName() map[string]string {
	requestCnMap := make(map[string]string)

	// 用户管理
	requestCnMap["/smart/user/enum"] = "用户-枚举列表"
	requestCnMap["/smart/user/list"] = "用户-用户列表及筛选"
	requestCnMap["/smart/user/info"] = "用户-用户详情"
	requestCnMap["/smart/user/save"] = "用户-新增/编辑用户"
	requestCnMap["/smart/user/del"] = "用户-删除"
	requestCnMap["/smart/user/updatepw"] = "用户-修改密码"
	requestCnMap["/smart/user/resetpw"] = "用户-重置密码"
	requestCnMap["/smart/user/updateuserexp"] = "用户-修改有效期"
	requestCnMap["/smart/user/changestatus"] = "用户-切换用户状态"
	requestCnMap["/smart/user/logout"] = "用户-退出登录"
	requestCnMap["/smart/user/loginfreepassa"] = "用户-所项目免密登录"

	// 系统管理
	requestCnMap["/smart/system/authinfo"] = "产品授权-查询"
	requestCnMap["/smart/system/authsave"] = "产品授权-授权"
	requestCnMap["/smart/system/generateProductID"] = "产品授权-生成产品id"
	requestCnMap["/smart/system/securities"] = "系统管理-创建安全配置"
	requestCnMap["/smart/system/initialinfo"] = "系统管理-安全配置初始化信息"
	requestCnMap["/smart/system/configbackupconfigsave"] = "配置备份-保存配置"
	requestCnMap["/smart/system/configbackupconfiginfo"] = "配置备份-配置信息"
	requestCnMap["/smart/system/configbackupnow"] = "配置备份-立即备份"
	requestCnMap["/smart/system/configbackuplist"] = "配置备份-列表"
	requestCnMap["/smart/system/configbackupdownload"] = "配置备份-下载"
	requestCnMap["/smart/system/configbackupdelete"] = "配置备份-删除"
	requestCnMap["/smart/system/configbackuprestore"] = "配置备份-恢复"
	requestCnMap["/smart/system/ipwhitesave"] = "系统设置-ip白名单-保存"
	requestCnMap["/smart/system/ipwhiteinfo"] = "系统设置-ip白名单-信息"
	requestCnMap["/smart/system/syslogsave"] = "系统设置-syslog服务-保存"
	requestCnMap["/smart/system/sysloginfo"] = "系统设置-syslog服务-信息"
	requestCnMap["/smart/system/networkconfigsave"] = "系统设置-网络配置-保存"
	requestCnMap["/smart/system/networkconfiginfo"] = "系统设置-网络配置-信息"
	requestCnMap["/smart/system/routelist"] = "系统设置-配置路由-列表"
	requestCnMap["/smart/system/routeadd"] = "系统设置-配置路由-增加"
	requestCnMap["/smart/system/routedelete"] = "系统设置-配置路由-删除"
	requestCnMap["/smart/system/monitorwarninfo"] = "系统设置-系统监控告警-信息"
	requestCnMap["/smart/system/monitorwarnsave"] = "系统设置-系统监控告警-保存"
	requestCnMap["/smart/system/targetipsave"] = "业务设置-测试目标黑白名单更新"
	requestCnMap["/smart/system/targetiplist"] = "业务设置-测试目标黑白名单查询"
	requestCnMap["/smart/system/getreverseiphost"] = "业务设置-远程监听查询"
	requestCnMap["/smart/system/reverseiphostsave"] = "业务设置-远程监听修改"
	requestCnMap["/smart/system/tcpblindtestsave"] = "业务设置-tcp盲测平台-保存"
	requestCnMap["/smart/system/tcpblindtestinfo"] = "业务设置-tcp盲测平台-信息"
	requestCnMap["/smart/system/httpblindtestsave"] = "业务设置-http盲测平台-保存"
	requestCnMap["/smart/system/httpblindtestinfo"] = "业务设置-http盲测平台-信息"
	requestCnMap["/smart/system/dnsblindtestsave"] = "业务设置-dns盲测平台-保存"
	requestCnMap["/smart/system/dnsblindtestinfo"] = "业务设置-dns盲测平台-信息"
	requestCnMap["/smart/system/curtasksinfo"] = "业务设置-任务并发配置-信息"
	requestCnMap["/smart/system/curtaskssave"] = "业务设置-任务并发配置-保存"
	requestCnMap["/smart/system/securityscanconcurrencyinfo"] = "系统设置-安全检查并发配置-信息"
	requestCnMap["/smart/system/securityscanconcurrencysave"] = "系统设置-安全检查并发配置-保存"
	requestCnMap["/smart/system/usescoreinfo"] = "业务设置-可以利用评分-信息"
	requestCnMap["/smart/system/usescoresave"] = "业务设置-可以利用评分-保存"
	requestCnMap["/smart/system/cpuinfo"] = "系统监控-cpu"
	requestCnMap["/smart/system/memoryinfo"] = "系统监控-内存"
	requestCnMap["/smart/system/diskinfo"] = "系统监控-磁盘"
	requestCnMap["/smart/system/uploadupgradefile"] = "升级还原-上传文件"
	requestCnMap["/smart/system/systemversion"] = "升级还原-系统版本信息"
	requestCnMap["/smart/system/confirmupgrade"] = "升级还原-确认升级"
	requestCnMap["/smart/system/upgradestatus"] = "升级还原-获取升级进度"
	requestCnMap["/smart/system/manualrollback"] = "升级还原-手动回滚"
	requestCnMap["/smart/system/generatetoken"] = "升级还原-秘钥生成"
	requestCnMap["/smart/system/tokenlist"] = "升级还原-秘钥列表"
	requestCnMap["/smart/system/nodedownload"] = "节点管理-下载节点安装包"
	requestCnMap["/smart/system/nodesetdistribute"] = "节点管理-设置是否开启分布式"
	requestCnMap["/smart/system/nodegetdistribute"] = "节点管理-获取是否开启分布式"
	requestCnMap["/smart/system/nodeadd"] = "节点管理-节点添加"
	requestCnMap["/smart/system/nodelist"] = "节点管理-节点列表"
	requestCnMap["/smart/system/nodedel"] = "节点管理-节点删除"
	requestCnMap["/smart/system/nodedisorenable"] = "节点管理-节点是否启用"
	requestCnMap["/smart/system/nodeallenable"] = "节点管理-所有可用节点"

	// 工具管理
	requestCnMap["/smart/tools/vulenum"] = "漏洞库-枚举"
	requestCnMap["/smart/tools/vullist"] = "漏洞库-列表"
	requestCnMap["/smart/tools/vuldetail"] = "漏洞库-详情"
	requestCnMap["/smart/tools/vuledit"] = "漏洞库-编辑"
	requestCnMap["/smart/tools/vuleditstatus"] = "漏洞库-修改状态"
	requestCnMap["/smart/tools/importvulnvulkit"] = "漏洞库-导入规则包"
	requestCnMap["/smart/tools/enum"] = "字典库-枚举"
	requestCnMap["/smart/tools/dictlist"] = "字典库-列表"
	requestCnMap["/smart/tools/dictinfo"] = "字典库-详情"
	requestCnMap["/smart/tools/dictdel"] = "字典库-删除"
	requestCnMap["/smart/tools/dictsetdefault"] = "字典库-设置默认字典"
	requestCnMap["/smart/tools/dictaddoredit"] = "字典库-新增或编辑"
	requestCnMap["/smart/tools/fingerenum"] = "指纹库-枚举"
	requestCnMap["/smart/tools/fingerlist"] = "指纹库-列表"
	requestCnMap["/smart/tools/addfinger"] = "指纹库-添加"
	requestCnMap["/smart/tools/editfinger"] = "指纹库-修改"
	requestCnMap["/smart/tools/fingerinfo"] = "指纹库-详情"
	requestCnMap["/smart/tools/delfinger"] = "指纹库-删除"
	requestCnMap["/smart/tools/testfinger"] = "指纹库-测试"
	requestCnMap["/smart/tools/testfingerresult"] = "指纹库-测试结果"
	requestCnMap["/smart/tools/supportiphostcreate"] = "辅助工具-IP域名绑定-创建/编辑"
	requestCnMap["/smart/tools/supportiphostlist"] = "辅助工具-IP域名绑定-列表"
	requestCnMap["/smart/tools/supportiphostdel"] = "辅助工具-IP域名绑定-删除"
	requestCnMap["/smart/tools/supportpingcreate"] = "辅助工具-Ping-创建"
	requestCnMap["/smart/tools/supportpingstop"] = "辅助工具-Ping-停止"
	requestCnMap["/smart/tools/supportpingresult"] = "辅助工具-Ping-结果"
	requestCnMap["/smart/tools/supporttraceroutecreate"] = "辅助工具-traceroute-创建"
	requestCnMap["/smart/tools/supporttraceroutestop"] = "辅助工具-traceroute-停止"
	requestCnMap["/smart/tools/supporttracerouteresult"] = "辅助工具-traceroute-结果"

	// 用户组管理
	requestCnMap["/smart/usergroup/page"] = "用户组列表"
	requestCnMap["/smart/usergroup/create"] = "新建用户组"
	requestCnMap["/smart/usergroup/update"] = "编辑用户组"
	requestCnMap["/smart/usergroup/select"] = "用户组选择"
	requestCnMap["/smart/usergroup/updatestatus"] = "用户组组员管理 用户组 与 用户 关联"

	// 用户组组员管理 用户组 与 用户 关联
	requestCnMap["/smart/usergroup/preselectionpage"] = "组员列表"
	requestCnMap["/smart/usergroup/alreadypage"] = "组内成员"
	requestCnMap["/smart/usergroup/relation"] = "保存至用户组"

	// 场景管理
	requestCnMap["/smart/scene/enum"] = "任务场景-枚举值"
	requestCnMap["/smart/scene/save"] = "任务场景-创建/更新"
	requestCnMap["/smart/scene/list"] = "任务场景-列表"
	requestCnMap["/smart/scene/vullist"] = "任务场景-漏洞列表"
	requestCnMap["/smart/scene/info"] = "任务场景-详情"
	requestCnMap["/smart/scene/copy"] = "任务场景-拷贝"
	requestCnMap["/smart/scene/setdefault"] = "任务场景-设置默认"
	requestCnMap["/smart/scene/del"] = "任务场景-删除"
	requestCnMap["/smart/scene/sceneoptions"] = "渗透任务-场景选项"
	requestCnMap["/smart/scene/graph"] = "渗透任务-场景选项"

	// 任务中心
	requestCnMap["/smart/task/enum"] = "渗透任务-枚举"
	requestCnMap["/smart/task/websitelogincheck"] = "渗透任务-验证站点是否能登陆"
	requestCnMap["/smart/task/save"] = "渗透任务-创建"
	requestCnMap["/smart/task/list"] = "渗透任务-列表"
	requestCnMap["/smart/task/del"] = "渗透任务-删除"
	requestCnMap["/smart/task/copy"] = "渗透任务-拷贝"
	requestCnMap["/smart/task/changestate"] = "渗透任务-修改任务运行状态"
	requestCnMap["/smart/task/getstate"] = "渗透任务-获取任务状态"
	requestCnMap["/smart/task/overview"] = "渗透任务-任务概览"
	requestCnMap["/smart/task/configinfo"] = "渗透任务-任务配置信息"
	requestCnMap["/smart/task/targetchangestate"] = "渗透任务-修改测试目标状态"
	requestCnMap["/smart/task/targetlist"] = "渗透任务-测试目标列表及筛选"
	requestCnMap["/smart/task/updatetargetusescore"] = "渗透任务-批量修改目标的利用评分和状态"
	requestCnMap["/smart/task/targetdel"] = "渗透任务-测试目标删除"
	requestCnMap["/smart/task/taskresultlist"] = "渗透任务-信息收集列表及筛选"
	requestCnMap["/smart/task/taskresultdel"] = "渗透任务-信息收集删除"
	requestCnMap["/smart/task/taskresultdetail"] = "渗透任务-信息收集详情"
	requestCnMap["/smart/task/vullist"] = "渗透任务-漏洞测试列表及筛选"
	requestCnMap["/smart/task/vulinfo"] = "渗透任务-漏洞测试详情"
	requestCnMap["/smart/task/getvulsnapshot"] = "渗透任务-查看漏洞截图"
	requestCnMap["/smart/task/vuldel"] = "渗透任务-漏洞测试删除"
	requestCnMap["/smart/task/vultest"] = "渗透任务-漏洞测试测试"
	requestCnMap["/smart/task/vulverify"] = "渗透任务-漏洞测试验证"
	requestCnMap["/smart/task/testvultest"] = "渗透任务-待测漏洞测试"
	requestCnMap["/smart/task/loglist"] = "渗透任务-测试日志列表及筛选"
	requestCnMap["/smart/task/loginfo"] = "渗透任务-测试日志详情"
	requestCnMap["/smart/task/apisave"] = "渗透任务-第三方创建接口"
	requestCnMap["/smart/task/progress"] = "渗透任务-获取进度"
	requestCnMap["/smart/task/apivullist"] = "渗透任务-漏洞测试列表及筛选"
	requestCnMap["/smart/task/addtarget"] = "渗透任务-动态添加目标"
	requestCnMap["/smart/task/addattackface"] = "渗透任务-动态添加攻击面"
	requestCnMap["/smart/task/addvul"] = "渗透任务-动态添加漏洞"
	requestCnMap["/smart/task/tasktargetmap"] = "渗透任务-路径图"
	requestCnMap["/smart/task/tasktargetmapnodedetail"] = "渗透任务-路径图节点详情"
	requestCnMap["/smart/task/taskthreeexport"] = "渗透任务-三方数据导出"
	requestCnMap["/smart/task/tasktopologymap"] = "渗透任务-攻击拓扑图"
	requestCnMap["/smart/task/tasktopologymapnodedetail"] = "渗透任务-攻击拓扑图-节点详情"
	requestCnMap["/smart/task/vulevidencelist"] = "漏洞取证-列表及筛选"
	requestCnMap["/smart/task/risktypeenum"] = "漏洞取证-风险类型枚举"
	requestCnMap["/smart/task/delvulevidence"] = "漏洞取证-删除漏洞取证列表信息"
	requestCnMap["/smart/task/vulevidenceinfo"] = "漏洞取证-漏洞取证详情信息"
	requestCnMap["/smart/task/remotesessionlist"] = "远程会话-列表及筛选"
	requestCnMap["/smart/task/delremotesession"] = "远程会话-删除列表"
	requestCnMap["/smart/task/remotesessioninfo"] = "远程会话-详情"
	requestCnMap["/smart/task/downloadfile"] = "远程会话-下载已下载文件"
	requestCnMap["/smart/task/delfile"] = "远程会话-删除已下载文件"
	requestCnMap["/smart/task/captureinfoenum"] = "远程会话-抓取信息枚举"
	requestCnMap["/smart/task/break"] = "远程会话-断开"
	requestCnMap["/smart/task/exceshell"] = "远程会话-利用shell"
	requestCnMap["/smart/task/captureinfo"] = "远程会话-抓取信息"
	requestCnMap["/smart/task/exceshellmany"] = "远程会话-批量收集信息"
	requestCnMap["/smart/task/flowtaskenum"] = "流量分析-枚举"
	requestCnMap["/smart/task/flowtasklist"] = "流量分析-任务列表"
	requestCnMap["/smart/task/flowtaskdel"] = "流量分析-任务删除"
	requestCnMap["/smart/task/flowtaskadd"] = "流量分析-创建任务"
	requestCnMap["/smart/task/changeflowtaskstatus"] = "流量分析-任务操作"
	requestCnMap["/smart/task/flowtaskstatus"] = "流量分析-任务状态"
	requestCnMap["/smart/task/flowtaskinfo"] = "流量分析-任务详情"
	requestCnMap["/smart/task/httpscert"] = "流量分析-https证书下载"
	requestCnMap["/smart/task/flowrisklist"] = "流量分析-漏洞列表"
	requestCnMap["/smart/task/flowriskinfo"] = "流量分析-漏洞详情"
	requestCnMap["/smart/task/flowriskdel"] = "流量分析-漏洞删除"
	requestCnMap["/smart/task/flowbaselist"] = "流量分析-被动流量列表"
	requestCnMap["/smart/task/flowbaseinfo"] = "流量分析-被动流量详情"
	requestCnMap["/smart/task/flowbasedel"] = "流量分析-被动流量删除"
	requestCnMap["/smart/task/flowloginfo"] = "流量分析-被动流量日志查询"
	requestCnMap["/smart/task/flowlogdel"] = "流量分析-被动流量日志清除"

	//报告中心
	requestCnMap["/smart/report/enum"] = "报告枚举"
	requestCnMap["/smart/report/list"] = "报告清单-列表及筛选"
	requestCnMap["/smart/report/download"] = "报告清单-下载"
	requestCnMap["/smart/report/del"] = "报告清单-删除"
	requestCnMap["/smart/report/save"] = "生成报告-保存"

	//日志管理
	requestCnMap["/smart/logs/enum"] = "日志管理-日志枚举"
	requestCnMap["/smart/logs/logauditlist"] = "日志管理-审计日志-列表"
	requestCnMap["/smart/logs/logauditempty"] = "日志管理-审计日志-清空"
	requestCnMap["/smart/logs/logbackupconfig"] = "日志管理-日志备份-配置"
	requestCnMap["/smart/logs/logbackupconfiginfo"] = "日志管理-日志备份-配置信息"
	requestCnMap["/smart/logs/setexptime"] = "日志管理-日志备份-设置日志过期时间"
	requestCnMap["/smart/logs/getexptime"] = "日志管理-日志备份-查询日志过期时间"
	requestCnMap["/smart/logs/logbackuplist"] = "日志管理-日志备份-列表"
	requestCnMap["/smart/logs/logbackupdownload"] = "日志管理-日志备份-下载"
	requestCnMap["/smart/logs/logbackupdelete"] = "日志管理-日志备份-删除"
	requestCnMap["/smart/logs/logbackupnow"] = "日志管理-日志备份-立即备份"

	// 三方工具
	requestCnMap["/smart/tripartite/xraysave"] = "xray-任务创建"
	requestCnMap["/smart/tripartite/xrayupload"] = "xray-任务导入"
	requestCnMap["/smart/tripartite/xraydel"] = "xray-任务删除"
	requestCnMap["/smart/tripartite/xraylist"] = "xray-任务列表"
	requestCnMap["/smart/tripartite/xraydetaillist"] = "xray-任务详情详情"
	requestCnMap["/smart/tripartite/burpsuitesave"] = "burpsuite-任务创建"
	requestCnMap["/smart/tripartite/burpsuiteupload"] = "burpsuite-任务导入"
	requestCnMap["/smart/tripartite/burpsuitedel"] = "burpsuite-任务删除"
	requestCnMap["/smart/tripartite/burpsuitelist"] = "burpsuite-任务列表"
	requestCnMap["/smart/tripartite/burpsuitedetaillist"] = "burpsuite-任务详情列表"
	requestCnMap["/smart/tripartite/wifiaplist"] = "wifi-可用wifi列表"
	requestCnMap["/smart/tripartite/wificreate"] = "wifi-任务创建"
	requestCnMap["/smart/tripartite/wifilist"] = "wifi-任务列表"
	requestCnMap["/smart/tripartite/wifidel"] = "wifi-任务删除"

	//bas
	requestCnMap["/smart/bas/enum"] = "bas-枚举接口"
	requestCnMap["/smart/bas/taskcreate"] = "bas-任务创建"
	requestCnMap["/smart/bas/receivresult"] = "bas-bas心跳及检测结果接收"
	requestCnMap["/smart/bas/basvulstat"] = "bas-漏洞测试统计"
	requestCnMap["/smart/bas/basvullist"] = "bas-漏洞测试列表"
	requestCnMap["/smart/bas/basvuldel"] = "bas-漏洞测试删除"
	requestCnMap["/smart/bas/bastruleimpor"] = "bas-规则导入"
	requestCnMap["/smart/bas/basruleenum"] = "bas-规则枚举"
	requestCnMap["/smart/bas/basruleget"] = "bas-规则列表"
	requestCnMap["/smart/bas/basruleinfo"] = "bas-规则详情"
	requestCnMap["/smart/bas/basruleedit"] = "bas-规则编辑"
	requestCnMap["/smart/bas/bastemplatecreate"] = "bas-剧本集创建"
	requestCnMap["/smart/bas/bastemplateget"] = "bas-剧本集列表"
	requestCnMap["/smart/bas/bastemplatebyid"] = "bas-剧本集详情"
	requestCnMap["/smart/bas/bastemplatedel"] = "bas-剧本集删除"
	requestCnMap["/smart/bas/bastemplatesetdefault"] = "bas-剧本集设置默认"
	requestCnMap["/smart/bas/basagentisonline"] = "bas-agent是否在线"
	requestCnMap["/smart/bas/bastaskget"] = "bas-任务列表"
	requestCnMap["/smart/bas/bastaskend"] = "bas-任务结束"
	requestCnMap["/smart/bas/bastaskdel"] = "bas-任务删除"
	requestCnMap["/smart/bas/bastasktargetpage"] = "bas-任务详情"
	requestCnMap["/smart/bas/bastasktargetlog"] = "bas-任务目标日志"
	requestCnMap["/smart/bas/bastasktargetdel"] = "bas-任务目标删除"
	requestCnMap["/smart/bas/basagentdownload"] = "bas-agent- 下载"
	requestCnMap["/smart/bas/basagentlist"] = "bas-agent- 列表"
	requestCnMap["/smart/bas/basagentlive"] = "bas-agent- 可用节点列表"
	requestCnMap["/smart/bas/basagentstatusedit"] = "bas-agent- 状态修改"

	// 一体化安全检查平台
	requestCnMap["/smart/baseline/test-conn"] = "主机安全-连接测试"
	requestCnMap["/smart/baseline/check"] = "主机安全-配置核查创建"
	requestCnMap["/smart/baseline/check/batch"] = "主机安全-批量配置核查创建"
	requestCnMap["/smart/baseline/check/progress"] = "主机安全-配置核查进度"
	requestCnMap["/smart/baseline/result"] = "主机安全-配置核查结果"
	requestCnMap["/smart/baseline/stat"] = "主机安全-配置核查统计"
	requestCnMap["/smart/baseline/tasks"] = "主机安全-配置核查任务列表"
	requestCnMap["/smart/baseline/task/targets"] = "主机安全-配置核查目标列表"
	requestCnMap["/smart/baseline/rules"] = "主机安全-配置核查规则"
	requestCnMap["/smart/baseline/rules/db"] = "主机安全-配置核查规则库"
	requestCnMap["/smart/baseline/rules/stats"] = "主机安全-配置核查规则统计"
	requestCnMap["/smart/baseline/rule/detail"] = "主机安全-配置核查规则详情"
	requestCnMap["/smart/baseline/rule/create"] = "主机安全-新增配置核查规则"
	requestCnMap["/smart/baseline/rule/update"] = "主机安全-编辑配置核查规则"
	requestCnMap["/smart/baseline/rule/delete"] = "主机安全-删除配置核查规则"
	requestCnMap["/smart/baseline/rules/import"] = "主机安全-导入配置核查规则"
	requestCnMap["/smart/baseline/enums"] = "主机安全-配置核查枚举"
	requestCnMap["/smart/hostsec/tasks/delete"] = "主机安全-删除任务"
	requestCnMap["/smart/vulnscan/cve/run"] = "主机安全-CVE漏洞扫描创建"
	requestCnMap["/smart/vulnscan/cve/batch"] = "主机安全-批量CVE漏洞扫描创建"
	requestCnMap["/smart/vulnscan/cve/progress"] = "主机安全-CVE漏洞扫描进度"
	requestCnMap["/smart/vulnscan/cve/tasks"] = "主机安全-CVE漏洞扫描任务列表"
	requestCnMap["/smart/vulnscan/cve/stat"] = "主机安全-CVE漏洞扫描统计"
	requestCnMap["/smart/vulnscan/cve/targets"] = "主机安全-CVE漏洞扫描目标列表"
	requestCnMap["/smart/vulnscan/cve/findings"] = "主机安全-CVE漏洞扫描发现列表"
	requestCnMap["/smart/malware/yara/run"] = "主机安全-YARA恶意代码检测创建"
	requestCnMap["/smart/malware/yara/batch"] = "主机安全-批量YARA恶意代码检测创建"
	requestCnMap["/smart/malware/yara/progress"] = "主机安全-YARA恶意代码检测进度"
	requestCnMap["/smart/malware/yara/result"] = "主机安全-YARA恶意代码检测结果"
	requestCnMap["/smart/malware/yara/tasks"] = "主机安全-YARA恶意代码检测任务列表"
	requestCnMap["/smart/malware/yara/stat"] = "主机安全-YARA恶意代码检测统计"
	requestCnMap["/smart/malware/yara/targets"] = "主机安全-YARA恶意代码检测目标列表"
	requestCnMap["/smart/malware/rules"] = "主机安全-病毒库规则列表"
	requestCnMap["/smart/malware/rule/detail"] = "主机安全-病毒库规则详情"
	requestCnMap["/smart/malware/rule/create"] = "主机安全-新增病毒库规则"
	requestCnMap["/smart/malware/rule/update"] = "主机安全-编辑病毒库规则"
	requestCnMap["/smart/malware/rule/delete"] = "主机安全-删除病毒库规则"
	requestCnMap["/smart/malware/rule/import"] = "主机安全-导入病毒库规则"
	requestCnMap["/smart/appsec/dynamic/run"] = "应用安全-动态扫描创建"
	requestCnMap["/smart/appsec/dynamic/list"] = "应用安全-动态扫描任务列表"
	requestCnMap["/smart/appsec/dynamic/detail"] = "应用安全-动态扫描详情"
	requestCnMap["/smart/appsec/appspecific/run"] = "应用安全-专项应用检测创建"
	requestCnMap["/smart/appsec/appspecific/list"] = "应用安全-专项应用检测任务列表"
	requestCnMap["/smart/appsec/appspecific/detail"] = "应用安全-专项应用检测详情"
	requestCnMap["/smart/datasec/db/test-conn"] = "数据安全-数据库连接测试"
	requestCnMap["/smart/datasec/db/run"] = "数据安全-数据库安全检查创建"
	requestCnMap["/smart/datasec/db/list"] = "数据安全-数据库安全检查任务列表"
	requestCnMap["/smart/datasec/db/detail"] = "数据安全-数据库安全检查详情"
	requestCnMap["/smart/datasec/sensitive/run"] = "数据安全-敏感数据扫描创建"
	requestCnMap["/smart/datasec/sensitive/list"] = "数据安全-敏感数据任务列表"
	requestCnMap["/smart/datasec/sensitive/detail"] = "数据安全-敏感数据任务详情"
	requestCnMap["/smart/datasec/task/clone-targets"] = "数据安全-复制历史任务目标"
	requestCnMap["/smart/datasec/task/rerun"] = "数据安全-再次检测"
	requestCnMap["/smart/datasec/task/delete"] = "数据安全-删除任务"
	requestCnMap["/smart/datasec/target/list"] = "数据安全-目标库列表"
	requestCnMap["/smart/datasec/target/save"] = "数据安全-保存目标库"
	requestCnMap["/smart/datasec/target/delete"] = "数据安全-删除目标库"
	requestCnMap["/smart/datasec/target/import"] = "数据安全-导入目标库"
	requestCnMap["/smart/datasec/target/export"] = "数据安全-导出目标库"
	requestCnMap["/smart/datasec/target/save-from-task"] = "数据安全-任务目标保存到目标库"
	requestCnMap["/smart/datasec/target/test-conn"] = "数据安全-目标库连接测试"
	requestCnMap["/smart/datasec/target/batch-test-conn"] = "数据安全-目标库批量连接测试"
	requestCnMap["/smart/datasec/rules"] = "数据安全-检测规则列表"
	requestCnMap["/smart/datasec/rules/stats"] = "数据安全-检测规则统计"
	requestCnMap["/smart/datasec/rules/reload"] = "数据安全-重载检测规则"
	requestCnMap["/smart/datasec/rules/import"] = "数据安全-导入检测规则"
	requestCnMap["/smart/datasec/rules/import-builtin"] = "数据安全-导入内置检测规则"
	requestCnMap["/smart/datasec/rules/cve-preview"] = "数据安全-CVE规则导入预览"
	requestCnMap["/smart/datasec/rules/import-cve"] = "数据安全-从CVE库导入规则"
	requestCnMap["/smart/datasec/rule/detail"] = "数据安全-检测规则详情"
	requestCnMap["/smart/datasec/rule/create"] = "数据安全-新增检测规则"
	requestCnMap["/smart/datasec/rule/update"] = "数据安全-编辑检测规则"
	requestCnMap["/smart/datasec/rule/delete"] = "数据安全-删除检测规则"

	//首页
	requestCnMap["/smart/homepage/taskinfostat"] = "首页-任务统计"
	requestCnMap["/smart/homepage/vulevidencestat"] = "首页-漏洞取证"
	requestCnMap["/smart/homepage/targetriskstat"] = "首页-目标统计"
	requestCnMap["/smart/homepage/taskvulriskstat"] = "首页-任务漏洞统计"
	requestCnMap["/smart/homepage/toolinfostat"] = "首页-渗透支撑"
	requestCnMap["/smart/homepage/vultypestat"] = "首页-漏洞类型统计"
	requestCnMap["/smart/homepage/vulfindtrendstat"] = "首页-漏洞发现趋势"
	requestCnMap["/smart/homepage/messagestat"] = "首页-最新消息统计模块"

	//报告验证接口
	requestCnMap["/smart/reportverify/upload"] = "报告验证-报告上传"
	requestCnMap["/smart/reportverify/tasklist"] = "报告验证-任务列表"
	requestCnMap["/smart/reportverify/taskdetail"] = "报告验证-任务详情"
	requestCnMap["/smart/reportverify/targetlist"] = "报告验证-目标列表"
	requestCnMap["/smart/reportverify/portlist"] = "报告验证-端口列表"
	requestCnMap["/smart/reportverify/vullist"] = "报告验证-漏洞列表"
	requestCnMap["/smart/reportverify/enum"] = "报告验证-枚举接口"
	requestCnMap["/smart/reportverify/stats"] = "报告验证-统计信息"
	requestCnMap["/smart/reportverify/taskstop"] = "报告验证-结束任务"
	requestCnMap["/smart/reportverify/taskdelete"] = "报告验证-删除任务"
	requestCnMap["/smart/reportverify/targetdelete"] = "报告验证-删除目标"
	requestCnMap["/smart/reportverify/vuldelete"] = "报告验证-删除漏洞"
	requestCnMap["/smart/reportverify/vuldetail"] = "报告验证-漏洞详情"

	return requestCnMap
}

func (r *requestCn) GetCnName(uri string) string {
	return r.AllCnName()[uri]
}
